### ISSUE TITLE
Problem with glob() pattern length

### ISSUE THREAD

**Issue by mmodler** [barryvdh/composer-cleanup-plugin#1]
Hi barry,

as a user of the former laravel cleanup plugin, i now tried your new composer cleanup plugin.

I run composer under win7 with git bash, and there the path length is limited to 260 chars:

```
Could not parse symfony/translation/Symfony/Component/Translation
({README*,CHANGELOG*,FAQ*,CONTRIBUTING*,HISTORY*,UPGRADING*,UPGRADE*,package*,demo,example,examples,doc,docs,readme*,.travis.yml,.scrutinizer.yml,phpunit.xml*,phpunit.php,test,tests,Tests}):
glob(): Pattern exceeds the maximum allowed length of 260 characters
```

I think a solution could be splitting patterns into multiple glob's? Might be a little slower, but composer operations aren't perfomance critical i think?

Would you change the glob code to work on win or accept a pr?

**Comment by barryvdh** [comment]
Sure, I accept a PR
