### ISSUE TITLE
Add a catch all rule which will use a default rule

### ISSUE THREAD

**Issue by mbrowniebytes** [barryvdh/composer-cleanup-plugin#11]
The catch all rule would clean all other packages which do not match an existing rule, by using a default rule; such as array($docs, $tests)
This would allow all packages to be cleaned

**Comment by Langmans** [comment]
+1

Building upon this idea:

Why not add something to the composer.json file so that specific folders/files matching a rule get cleaned up?, for example (regex matching):

``` json
{
    "cleanup": {
        "files": [".*/(readme|changelog|license|phpunit.*)(\\.(md|txt|rst))?"],
        "directories":[".*/(test|doc)s?$"]
    }
}
```

**Comment by barryvdh** [comment]
Some are safe, but tests are not by default safe to delete, because some autoload/extend them.
