### ISSUE TITLE
composer-cleanup-plugin or composer-cleanup-login?

### ISSUE THREAD

**Issue by mmodler** [barryvdh/composer-cleanup-plugin#2]
Hi barry,

the github repo is named composer-cleanup-plugin, the composer.json name is composer-cleanup-login. Perhaps you like to normalize this to avoid confusion?

**Comment by barryvdh** [comment]
Should be plugin indeed :(
Can I just change that? Not really sure.

**Comment by barryvdh** [comment]
Changed to `https://packagist.org/packages/barryvdh/composer-cleanup-plugin` and deprecated old one.
