### ISSUE TITLE
Doc/Test files in subdirectories

### ISSUE THREAD

**Issue by mmodler** [barryvdh/composer-cleanup-plugin#8]
In my test project some files aren't deleted (former laravel-vendor-cleanup did):

vendor/laravel/framework/src/Illuminate/Database/README.md
vendor/laravel/framework/src/Illuminate/Queue/README.md
vendor/laravel/framework/src/Illuminate/Workbench/stubs/phpunit.xml
vendor/nikic/php-parser/grammar/README.md

what should we do about it? *README* default rules - is it secure? Package specific rules?

**Comment by mmodler** [comment]
Any thoughts on this?

**Comment by barryvdh** [comment]
Yeah I left the readme because it might be useful I think. Guess it could be removed.
Stubs should not be removed.

**Comment by mmodler** [comment]
Ok, lets leave it for now.
